apps/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("",views.BlogView.as_view(), name='blog'),
    path("code/",views.CodeView.as_view(), name='code'),
    path("economic/",views.EconomicView.as_view(), name='economic'),
    path("life/",views.LifeView.as_view(), name='life'),
    path("news/",views.NewsView.as_view(), name='news'),
    path("tags/",views.TagsView.as_view(), name='tags'),
    path("list/",views.blog_list, name='list'),
    path("show/<int:blog_id>",views.BlogShowView.as_view(), name='show')
]

apps/index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path("",views.IndexView.as_view(), name='index'),
    path("login/",views.loginview, name='login'),
    path("register/",views.register, name='register'),
    path("search/",views.search, name='search'),
    path("logout/",views.LogoutView.as_view(), name='logout'),
    path("message/",views.UserInfoView.as_view(), name='message'),
    path("change_nickname/",views.change_nickname, name='change_nickname'),
    path("bind_email/",views.bind_email, name='bind_email'),
    path("send_verification_code/",views.send_verification_code, name='send_verification_code'),
    path("change_password/",views.change_password, name='change_password'),
    path("forgot_password/",views.forgot_password, name='forgot_password'),
    path("show/<int:blog_id>",views.IndexShowView.as_view(), name='show'),
    path("map/", views.MapView.as_view(), name='map'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import  static
from django.conf import settings

admin.site.site_title = 'YLZ-个人博客管理系统'
admin.site.site_header = 'YLZ-个人博客管理系统'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('user/', include('user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/index/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username_or_email = forms.CharField(label="用户名",widget=forms.TextInput(attrs={'class':'form-control',"placeholder":"请输入用户名或邮箱"}))
    password = forms.CharField(label="密码",widget=forms.PasswordInput(attrs={'class':'form-control',"placeholder":"请输入密码"}))

    def clean(self):
        username_or_email = self.cleaned_data["username_or_email"]
        password = self.cleaned_data["password"]
        user = auth.authenticate(username=username_or_email, password=password)
        if user is None:
            if  User.objects.filter(email=username_or_email).exists():
                username = User.objects.get(email=username_or_email).username
                user = auth.authenticate(username=username, password=password)
                if not user is None:
                    self.cleaned_data["user"] = user
                    return self.cleaned_data
            raise forms.ValidationError("用户名或者密码不正确")
        else:
            self.cleaned_data["user"] = user
        return self.cleaned_data

class RegForm(forms.Form):
    username = forms.CharField(label='用户名',
                               max_length=30,
                               min_length=3,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '请输入3-30位用户名'}))
    email = forms.EmailField(label='邮箱',
                               widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '请输入邮箱'}))
    password = forms.CharField(label='密码',
                               min_length=6,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '请输入密码'}))
    password_again = forms.CharField(label='再输入一次密码',
                               min_length=6,
                               widget=forms.PasswordInput(
                               attrs={'class': 'form-control', 'placeholder': '再输入一次密码'}))
    # 验证码
    verification_code = forms.CharField(label="验证码", required=False,
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control', "placeholder": "点击“发生验证码”到邮箱"}))
    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(RegForm, self).__init__(*args, **kwargs)

    def clean(self):
    # 判断验证码
        code = self.request.session.get("register_code", "")
        verification_code = self.cleaned_data.get("verification_code", "")
        if not (code != "" and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("用户名已存在")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱已存在')
        return email

    def clean_password_again(self):
        password = self.cleaned_data['password']
        password_again = self.cleaned_data['password_again']
        if password != password_again:
            raise forms.ValidationError('两次输入的密码不一致')
        return password_again

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get("verification_code", "").strip()
        if verification_code == "":
            raise forms.ValidationError("验证码不能为空")
        return verification_code

class ChangeNicknameForm(forms.Form):
    nickname_new = forms.CharField(label="新的昵称",max_length=20,
                               widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "请输入新的昵称"}))

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangeNicknameForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登录
        if self.user.is_authenticated:
            self.cleaned_data['user'] = self.user
        else:
            raise forms.ValidationError('用户尚未登录')
        return self.cleaned_data

    def clean_nickname_new(self):
        nickname_new = self.cleaned_data.get("nickname_new","").strip()

        if nickname_new == "":
            raise forms.ValidationError("新的昵称不能为空")
        return nickname_new

class BindEmailForm(forms.Form):
    #邮箱
    email = forms.CharField(label="邮箱",
                           widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "请输入正确的邮箱"}))
    #验证码
    verification_code = forms.CharField(label="验证码",required=False,
                            widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "点击“发生验证码”到邮箱"}))
    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(BindEmailForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 判断用户是否登录
        if self.request.user.is_authenticated:
            self.cleaned_data['user'] = self.request.user
        else:
            raise forms.ValidationError('用户尚未登录')
        # 判断用户是否已绑定邮箱
        if self.request.user.email != "":
            raise forms.ValidationError("您已经绑定邮箱")
        # 判断验证码
        code = self.request.session.get("bind_email_code","")
        verification_code = self.cleaned_data.get("verification_code","")
        if not(code != "" and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return self.cleaned_data

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("该邮箱已经被绑定")
        return email

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get("verification_code", "").strip()
        if verification_code == "":
            raise forms.ValidationError("验证码不能为空")
        return verification_code

class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(
        label='旧的密码',
        widget=forms.PasswordInput(
            attrs={'class':'form-control', 'placeholder':'请输入旧的密码'}
        )
    )
    new_password = forms.CharField(
        label='新的密码',
        widget=forms.PasswordInput(
            attrs={'class':'form-control', 'placeholder':'请输入新的密码'}
        )
    )
    new_password_again = forms.CharField(
        label='请再次输入新的密码',
        widget=forms.PasswordInput(
            attrs={'class':'form-control', 'placeholder':'请再次输入新的密码'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'user' in kwargs:
            self.user = kwargs.pop('user')
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        # 验证新的密码是否一致
        new_password = self.cleaned_data.get('new_password', '')
        new_password_again = self.cleaned_data.get('new_password_again', '')
        if new_password != new_password_again or new_password == '':
            raise forms.ValidationError('两次输入的密码不一致')
        return self.cleaned_data

    def clean_old_password(self):
        # 验证旧的密码是否正确
        old_password = self.cleaned_data.get('old_password', '')
        if not self.user.check_password(old_password):
            raise forms.ValidationError('旧的密码错误')
        return old_password



class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(
        label='邮箱',
        widget=forms.EmailInput(
            attrs={'class':'form-control', 'placeholder':'请输入绑定过的邮箱'}
        )
    )
    verification_code = forms.CharField(
        label='验证码',
        required=False,
        widget=forms.TextInput(
            attrs={'class':'form-control', 'placeholder':'点击“发送验证码”发送到邮箱'}
        )
    )
    new_password = forms.CharField(
        label='新的密码',
        widget=forms.PasswordInput(
            attrs={'class':'form-control', 'placeholder':'请输入新的密码'}
        )
    )
    new_password_again = forms.CharField(
        label='请再次输入新的密码',
        widget=forms.PasswordInput(
            attrs={'class':'form-control', 'placeholder':'请再次输入新的密码'}
        )
    )

    def __init__(self, *args, **kwargs):
        if 'request' in kwargs:
            self.request = kwargs.pop('request')
        super(ForgotPasswordForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data['email'].strip()
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError('邮箱不存在')
        return email

    def clean_verification_code(self):
        verification_code = self.cleaned_data.get('verification_code', '').strip()
        if verification_code == '':
            raise forms.ValidationError('验证码不能为空')
        # 判断验证码
        code = self.request.session.get('forgot_password_code', '')
        verification_code = self.cleaned_data.get('verification_code', '')
        if not (code != '' and code == verification_code):
            raise forms.ValidationError('验证码不正确')
        return verification_code

    def clean(self):
        # 验证新的密码是否一致
        new_password = self.cleaned_data.get('new_password', '')
        new_password_again = self.cleaned_data.get('new_password_again', '')
        if new_password != new_password_again or new_password == '':
            raise forms.ValidationError('两次输入的密码不一致')
        return self.cleaned_data

templates/index/base.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="baidu-site-verification" content="MeBXvKNhZt" />
<meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}
<title>YLZ个人博客 -- 勤记录 懂分享</title>
    {% endblock %}
{% block meta %}
<meta name="keywords" content="开源社区,python开源,个人博客,财经主题，五味生活，新闻资讯">
<meta name="description" content="YLZ的个人网站，记录生活的瞬间，分享python学习的心得，提供最新的财经新闻资讯，静静寻觅生活的美好">
{% endblock %}
{% block script %}
{% endblock %}
<link rel="stylesheet" type="text/css" href="../../static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="../../static/css/nprogress.css">
<link rel="stylesheet" type="text/css" href="../../static/css/style.css">
<link rel="stylesheet" type="text/css" href="../../static/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="../../static/images/icon.png">
<link rel="shortcut icon" href="../../static/images/favicon.ico">
<script src="../../static/js/jquery-2.1.4.min.js"></script>
<script src="../../static/js/nprogress.js"></script>
<script src="../../static/js/jquery.lazyload.min.js"></script>



<!--[if gte IE 9]>
  <script src="../../static/js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="../../static/js/html5shiv.min.js" type="text/javascript"></script>
  <script src="../../static/js/respond.min.js" type="text/javascript"></script>
  <script src="../../static/js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>
<body class="user-select">
<header class="header">
<nav class="navbar navbar-default" id="navbar">
<div class="container">
  <div class="header-topbar hidden-xs link-border">
	<ul class="site-nav topmenu">
	  <li><a href="{% url 'blog:tags' %}" rel="nofollow">标签云</a></li>
		<li><a href="" rel="nofollow" >读者墙</a></li>
		<li><a href="" rel="nofollow" title="RSS订阅" >
			<i class="fa fa-rss">
			</i> RSS订阅
		</a></li>
        {% if user.is_authenticated %}
        <li class="dropdown">
          用户名：<span class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user }} <span class="caret"></span></span>
          <ul class="dropdown-menu">
              <li><a href="{% url 'index:message' %}">个人资料</a></li> <br>
              {% if user.is_staff or user.is_superuser %}
                <li><a href="{% url 'admin:index' %}">后台管理</a></li> <br>
              {% endif %}
              <li><a href="{% url 'index:logout' %}?form={{ request.get_full_path }}" >退出</a></li>
          </ul>
        </li>
        {% else %}
            <li class="nav navbar-nav navbar-right"><a class ="btn btn-primary" href="{% url 'index:login' %}?form={{ request.get_full_path }}" style="display: inline;color: #2b2b36">登录</a>
                <a class ="btn btn-danger" href="{% url 'index:register' %}?form={{ request.get_full_path }}" style="display: inline;color: #2b2b36">注册</a>
            </li>
        {% endif %}
	</ul>

			 勤记录 懂分享</div>
  <div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false"> <span class="sr-only"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
	<h1 class="logo hvr-bounce-in"><a href="{% url 'index:index' %}" title="YLZ个人博客"><img src="../../static/images/logo.png" alt="YLZ个人博客"></a></h1>
  </div>
  <div class="collapse navbar-collapse" id="header-navbar">
	<ul class="nav navbar-nav navbar-right">
	  <li><a data-cont="YLZ-Blog主题" title="YLZ-Blog主题" href="{% url 'index:index' %}">首页</a></li>
	  <li><a data-cont="YLZ-Bolg主题" title="YLZ-Bolg主题" href="{% url 'blog:blog' %}" >YLZ-Blog主题</a></li>
	  <li><a data-cont="IT技术笔记" title="IT技术笔记" href="{% url 'blog:code' %}" >IT技术笔记</a></li>
	  <li><a data-cont="财经主题" title="财经主题" href="{% url 'blog:economic' %}" >财经主题</a></li>
	  <li><a data-cont="五味生活" title="五味生活" href="{% url 'blog:life' %}" >五味生活</a></li>
	  <li><a data-cont="资讯分享" title="资讯分享" href="{% url 'blog:news' %}" >资讯分享</a></li>
	</ul>
  </div>
</div>
</nav>
</header>

{% block main %}{% endblock %}

<script src="http://static.tctip.com/tctip-1.0.0.min.js"></script>
  <script>
  new tctip({
    top: '20%',
    button: {
      id: 9,
      type: 'dashang',
    },
    list: [
      {
        type: 'alipay',
        qrImg: '../../static/images/zhifubao.png'
      }, {
        type: 'wechat',
        qrImg: '../../static/images/weixin.png'
      }
    ]
  }).init()
  </script>

{% block aside %}{% endblock %}

<div class="widget widget_hot">
	  <h3>热门文章推荐</h3>
	  <ul>
            {% for blog in blog_all %}
			<li><a title="{{ blog.title }}" href="{% url 'blog:show' blog.id %}" ><span class="thumbnail">
                {% if blog.img_url.url != "" %}
				    <img class="thumb" data-original="{{ blog.img_url.url }}" src="{{ blog.img_url.url }}" alt="{{ blog.title }}"  style="display: block;">
                {% else %}
                    <img class="thumb" data-original="../../static/images/YLZ个人博客.png" src="../../static/images/YLZ个人博客.png" alt="{{ blog.title }}"  style="display: block;">
                 {% endif %}
			</span><span class="text">{{ blog.title }}</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
				{{ blog.created_time |date:"Y-m-d" }}
			</span><span class="muted"><i class="glyphicon glyphicon-globe"></i>{{ blog.author }}</span></a></li>
            {% endfor %}
	  </ul>
 </div>
 <div class="widget widget_sentence">    
	<a href="{% url 'blog:life' %}" target="_blank"  title="专业网站建设" >
	<img style="width: 100%" src="../../static/images/201610241224221511.jpg" alt="专业网站建设" ></a>
 </div>
 <div class="widget widget_sentence">    
	<a href="#" target="_blank" rel="nofollow" title="YLZ个人博客--勤记录 懂分享" >
	<img style="width: 100%" src="../../static/images/ad.png" alt="YLZ个人博客--勤记录 懂分享" ></a>
 </div>
<div class="widget widget_sentence">
  <h3>友情链接</h3>
  <div class="widget-sentence-link">
	<a href="{% url 'blog:news' %}" title="网站建设" target="_blank" >网站建设</a>&nbsp;&nbsp;
	<a href="http://www.aiqingbinguan.com" title="芒果商务网" target="_blank" >芒果商务网</a>&nbsp;&nbsp;
	<a href="http://www.qisexiu.com" title="梨子商务网" target="_blank" >梨子商务网</a>&nbsp;&nbsp;
	<a href="http://www.woleting.com" title="香蕉商务网" target="_blank" >香蕉商务网</a>&nbsp;&nbsp;
  </div>
</div>
</aside>
</section>
<footer class="footer">
<div class="container">
     <p>Copyright &copy; 2019.Company name All rights reserved. 网站备案号<a  href="http://www.beian.miit.gov.cn/" target="_blank">  闽ICP备19019404号-1 </a></p><br>
     <p>YLZ 个人博客--勤记录 懂分享  <a href="{% url 'index:map' %}">网站地图</a>   网站的文章大部分来自网络，如果有侵犯您的权益，请联系站长。</p>
	 <script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?29f7c822c701badc7c27df0872eec830";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
</div>
<div id="gotop"><a class="gotop"></a></div>
</footer>
<script src="../../static/js/jquery.ias.js"></script>
<script src="../../static/js/bootstrap.min.js"></script>
<script src="../../static/js/scripts.js"></script>
<script>
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script>

{% block script_extends %}{% endblock %}

</body>
</html>

templates/index/base2.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta name="baidu-site-verification" content="MeBXvKNhZt" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% block meta %}
<meta name="keywords" content="开源社区,python开源,个人博客,财经主题，五味生活，新闻资讯">
<meta name="description" content="YLZ的个人网站，记录生活的瞬间，分享python学习的心得，提供最新的财经新闻资讯，静静寻觅生活的美好">
{% endblock %}
{% block title %} <title>YLZ个人博客 -- 勤记录 懂分享</title> {% endblock %}
<link rel="stylesheet" type="text/css" href="../../static/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="../../static/css/nprogress.css">
<link rel="stylesheet" type="text/css" href="../../static/css/style.css">
<link rel="stylesheet" type="text/css" href="../../static/css/font-awesome.min.css">
<link rel="apple-touch-icon-precomposed" href="../../static/images/icon.png">
<link rel="shortcut icon" href="../../static/images/favicon.ico">
<script src="../../static/js/jquery-2.1.4.min.js"></script>
<script src="../../static/js/nprogress.js"></script>
<script src="../../static/js/jquery.lazyload.min.js"></script>
<!--[if gte IE 9]>
<script src="js/jquery-1.11.1.min.js" type="text/javascript"></script>
<script src="js/html5shiv.min.js" type="text/javascript"></script>
<script src="js/respond.min.js" type="text/javascript"></script>
<script src="js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
<script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
<style type="text/css">
	.panel
	{
		padding: 80px 20px 0px;
		min-height: 400px;
		cursor: default;
	}
	.text-center
	{
		margin: 0 auto;
		text-align: center;
		border-radius: 10px;
		max-width: 900px;
		-moz-box-shadow: 0px 0px 5px rgba(0,0,0,.3);
		-webkit-box-shadow: 0px 0px 5px rgba(0,0,0,.3);
		box-shadow: 0px 0px 5px rgba(0,0,0,.1);
	}
	.float-left
	{
		float: left !important;
	}
	.float-right
	{
		float: right !important;
	}
	img
	{
		border: 0;
		vertical-align: bottom;
	}
	h2
	{
		padding-top: 20px;
		font-size: 20px;
	}
	.padding-big
	{
		padding: 20px;
	}
	.alert
	{
		border-radius: 5px;
		padding: 15px;
		border: solid 1px #ddd;
		background-color: #f5f5f5;
	}
</style>
</head>
<body class="user-select">
<header class="header">
<nav class="navbar navbar-default" id="navbar">
<div class="container">
  <div class="header-topbar hidden-xs link-border">
	<ul class="site-nav topmenu">
		<li><a href="{% url 'blog:tags' %}" >标签云</a></li>
		<li><a href="" rel="nofollow" >读者墙</a></li>
		<li><a href="" rel="nofollow" title="RSS订阅" >
			<i class="fa fa-rss">
			</i> RSS订阅
		</a></li>
        {% if user.is_authenticated %}
        <li class="dropdown">
          用户名：<span class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user }} <span class="caret"></span></span>
          <ul class="dropdown-menu">
             <li><a href="{% url 'index:message' %}">个人资料</a></li> <br>
              {% if user.is_staff or user.is_superuser %}
                <li><a href="{% url 'admin:index' %}">后台管理</a></li> <br>
              {% endif %}
              <li><a href="{% url 'index:logout' %}?form={{ request.get_full_path }}" >退出</a></li>
          </ul>
        </li>
        {% else %}
            <li class="nav navbar-nav navbar-right"><a class ="btn btn-primary" href="{% url 'index:login' %}?form={{ request.get_full_path }}" style="display: inline;color: #2b2b36">登录</a>
                <a class ="btn btn-danger" href="{% url 'index:register' %}?form={{ request.get_full_path }}" style="display: inline;color: #2b2b36">注册</a>
            </li>
        {% endif %}
	</ul>
			 勤记录 懂分享 </div>
  <div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false"> <span class="sr-only"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
	<h1 class="logo hvr-bounce-in"><a href="#" title="YLZ-Blog个人独立博客"><img src="../../static/images/logo.png" alt="YLZ-Blog个人独立博客"></a></h1>
  </div>
  <div class="collapse navbar-collapse" id="header-navbar">
	<form class="navbar-form visible-xs" action="" method="post">
	  <div class="input-group">
		<input type="text" name="keyword" class="form-control" placeholder="请输入关键字" maxlength="20" autocomplete="off">
		<span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span> </div>
	</form>
	<ul class="nav navbar-nav navbar-right">
	  <li><a data-cont="YLZ-Blog主题" title="YLZ-Blog主题" href="{% url 'index:index' %}">首页</a></li>
	  <li><a data-cont="YLZ-Bolg主题" title="YLZ-Bolg主题" href="{% url 'blog:blog' %}" >YLZ-Blog主题</a></li>
	  <li><a data-cont="IT技术笔记" title="IT技术笔记" href="{% url 'blog:code' %}" >IT技术笔记</a></li>
	  <li><a data-cont="财经主题" title="财经主题" href="{% url 'blog:economic' %}" >财经主题</a></li>
	  <li><a data-cont="五味生活" title="五味生活" href="{% url 'blog:life' %}" >五味生活</a></li>
	  <li><a data-cont="资讯分享" title="资讯分享" href="{% url 'blog:news' %}" >资讯分享</a></li>
	</ul>
  </div>
</div>
</nav>
</header>
<section class="container">
    {% block main %}

    {% endblock %}
</section>
<footer class="footer">
<div class="container">
	<p>Copyright &copy; 2019.Company name All rights reserved. 网站备案号<a  href="http://www.beian.miit.gov.cn/" target="_blank">  闽ICP备19019404号-1 </a></p><br>
    <p>YLZ 个人博客--勤记录 懂分享  <a href="{% url 'index:map' %}">网站地图</a>   网站的文章大部分来自网络，如果有侵犯您的权益，请联系站长。</p>
  </div>
<div id="gotop" style="display: block;"><a class="gotop" ></a>
</div>
</footer>
<script src="../../static/js/bootstrap.min.js"></script>
<script src="../../static/js/jquery.ias.js"></script>
<script src="../../static/js/scripts.js"></script>
{% block script_extend %}{% endblock %}
</body>
</html>

templates/index/message.html
{% extends "index/base2.html" %}
{% block title %}
<title>个人中心 -- YLZ个人博客</title>
{% endblock %}

{% block main %}
    <div class="content-wrap">
        <div class="content">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1">
                {% if user.is_authenticated %}
                    <h2>{{ user.username }}</h2><br>
                    <ul>
                         {% if user.profile.nickname %}
                             <li>昵称：{{ user.profile.nickname }}  <a href="{% url 'index:change_nickname' %}?from={{ request.get_full_path }}">修改或添加昵称</a></li></li>
                         {% else %}
                            <li>用户：{{ user.username }} 暂无昵称 <a href="{% url 'index:change_nickname' %}?from={{ request.get_full_path }}">修改或添加昵称</a></li></li>
                         {% endif %}
                        <li>邮箱：{% if user.email %} {{ user.email }} {% else %} 未绑定  <a href="{% url 'index:bind_email' %}">
                        绑定邮箱</a>{% endif %}</li>
                        <li>上一次登录时间：{{ user.last_login|date:"Y-m-d H:i:s" }}</li>
                        <li><a href="{% url 'index:change_password' %}">修改密码</a></li>
                    </ul>
                {% else %}
                    <span>未登录，正在跳转到首页...</span>
                    <script type="text/javascript">
                    　　function jumurl(){
                    　　window.location.href = '/';
                    　　}
                    　　setTimeout(jumurl,3000);
                　　</script>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}