apps/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("",views.BlogView.as_view(), name='blog'),
    path("code/",views.CodeView.as_view(), name='code'),
    path("economic/",views.EconomicView.as_view(), name='economic'),
    path("life/",views.LifeView.as_view(), name='life'),
    path("news/",views.NewsView.as_view(), name='news'),
    path("tags/",views.TagsView.as_view(), name='tags'),
    path("list/",views.blog_list, name='list'),
    path("show/<int:blog_id>",views.BlogShowView.as_view(), name='show')
]

apps/index/urls.py
from django.urls import path
from . import views

app_name = 'index'

urlpatterns = [
    path("",views.IndexView.as_view(), name='index'),
    path("login/",views.loginview, name='login'),
    path("register/",views.register, name='register'),
    path("search/",views.search, name='search'),
    path("logout/",views.LogoutView.as_view(), name='logout'),
    path("message/",views.UserInfoView.as_view(), name='message'),
    path("change_nickname/",views.change_nickname, name='change_nickname'),
    path("bind_email/",views.bind_email, name='bind_email'),
    path("send_verification_code/",views.send_verification_code, name='send_verification_code'),
    path("change_password/",views.change_password, name='change_password'),
    path("forgot_password/",views.forgot_password, name='forgot_password'),
    path("show/<int:blog_id>",views.IndexShowView.as_view(), name='show'),
    path("map/", views.MapView.as_view(), name='map'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import  static
from django.conf import settings

admin.site.site_title = 'YLZ-个人博客管理系统'
admin.site.site_header = 'YLZ-个人博客管理系统'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('user/', include('user.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.contrib .auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
# Create your models here.

class BlogType(models.Model):
    blog_type = models.CharField(max_length=20,verbose_name="博客类型",help_text="博客类型")
    is_delete = models.BooleanField(default=False, verbose_name='逻辑删除', help_text="逻辑删除")

    def __str__(self):
        return self.blog_type



class Blogs(models.Model):
    title = models.CharField(max_length=50,verbose_name="博客标题",help_text="博客标题")
    blog_type = models.ForeignKey(BlogType, on_delete=models.DO_NOTHING,verbose_name="博客类型",help_text="博客类型")
    author = models.ForeignKey(User,on_delete=models.DO_NOTHING,verbose_name="博客作者",help_text="博客作者")
    read_num = models.IntegerField(default=0,verbose_name="阅读次数", help_text="阅读次数")
    text = models.TextField(max_length=300,default="",verbose_name="文章摘要", help_text="文章摘要")
    content = RichTextUploadingField(verbose_name="文章", help_text="文章")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="发布时间", help_text="发布时间")
    img_url = models.ImageField(upload_to='blog', default="", blank=True)  # upload_to指定图片上传的途径，如果不存在则自动创建
    tags = TaggableManager()
    is_delete = models.BooleanField(default=False, verbose_name='逻辑删除', help_text="逻辑删除")
    # is_delete = models.BooleanField(default=False, verbose_name='逻辑删除')


    def __str__(self):
        return "<Blog: %s>" % self.title

    class Meta:
        ordering = ["id",'-created_time']
        db_table = "tb_mysite"  # 指明数据库表名
        verbose_name = "YLZ-博客"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

class Message(models.Model):
    title = models.CharField(max_length=50, verbose_name="标题", help_text="标题")
    created_time = models.DateTimeField(auto_now_add=True, verbose_name="发布时间", help_text="发布时间")
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name="作者", help_text="作者")
    read_num = models.IntegerField(default=0, verbose_name="阅读次数", help_text="阅读次数")
    is_delete = models.BooleanField(default=False, verbose_name='逻辑删除', help_text="逻辑删除")

    def __str__(self):
        return "<Message: %s>" % self.title

    class Meta:
        ordering = ["id",'-created_time']
        db_table = "tb_message"  # 指明数据库表名
        verbose_name = "留言板"  # 在admin站点中显示的名称
        verbose_name_plural = verbose_name  # 显示的复数名称

apps/blog/views.py
from django.shortcuts import render,get_object_or_404
from django.views  import View
from .models import Blogs
from comment.models import Comment
from comment.forms import CommentForm
from django.contrib.contenttypes.models import ContentType
import random
from django.core.paginator import Paginator


# Create your views here.


class BlogView(View):
    '''
    YLZ-Blog 主题
    '''

    def get(self,request):
        article_list = Blogs.objects.all()
        news_all_list = Blogs.objects.filter(blog_type=1).order_by("-created_time")
        blog_all = Blogs.objects.all().order_by("-read_num")[:8]  # 推荐的文章
        tags = Blogs.tags.all()
        tags = random.sample(list(tags),10)
        paginator = Paginator(news_all_list, 10)
        page_num = request.GET.get('page', 1)
        page_of_news = paginator.get_page(page_num)
        blogs = page_of_news.object_list
        return render(request,"blog/blog_list.html",locals())

class CodeView(View):
    '''
    IT技术笔记
    '''

    def get(self,request):
        news_all_list = Blogs.objects.filter(blog_type=2).order_by("-created_time")
        blog_all = Blogs.objects.all().order_by("-read_num")[:8]  # 推荐的文章
        tags = Blogs.tags.all()
        tags = random.sample(list(tags), 10)
        paginator = Paginator(news_all_list, 10)
        page_num = request.GET.get('page', 1)
        page_of_news = paginator.get_page(page_num)
        blogs = page_of_news.object_list
        return render(request,"blog/code_list.html",locals())

class EconomicView(View):
    '''
    财经主题
    '''

    def get(self,request):
        article_list = Blogs.objects.all()
        news_all_list = Blogs.objects.filter(blog_type=3).order_by("-created_time")
        blog_all = Blogs.objects.all().order_by("-read_num")[:8]  # 推荐的文章
        tags = Blogs.tags.all()
        tags = random.sample(list(tags),10)
        paginator = Paginator(news_all_list, 10)
        page_num = request.GET.get('page', 1)
        page_of_news = paginator.get_page(page_num)
        blogs = page_of_news.object_list
        return render(request,"blog/economic_list.html",locals())

class LifeView(View):
    '''
    五味生活
    '''

    def get(self,request):
        article_list = Blogs.objects.all()
        news_all_list = Blogs.objects.filter(blog_type=4).order_by("-created_time")
        blog_all = Blogs.objects.all().order_by("-read_num")[:8]  # 推荐的文章
        tags = Blogs.tags.all()
        tags = random.sample(list(tags),10)
        paginator = Paginator(news_all_list, 10)
        page_num = request.GET.get('page', 1)
        page_of_news = paginator.get_page(page_num)
        blogs = page_of_news.object_list
        return render(request,"blog/life_list.html",locals())


class NewsView(View):
    '''
    资讯分享
    '''

    def get(self,request):
        article_list = Blogs.objects.all()
        news_all_list = Blogs.objects.filter(blog_type=5).order_by("-created_time")
        blog_all = Blogs.objects.all().order_by("-read_num")[:8]  # 推荐的文章
        tags = Blogs.tags.all()
        tags = random.sample(list(tags),10)
        paginator = Paginator(news_all_list, 10)
        page_num = request.GET.get('page', 1)
        page_of_news = paginator.get_page(page_num)
        blogs = page_of_news.object_list
        return render(request,"blog/news_list.html",locals())

class BlogShowView(View):
    '''
    Blog详细页
    '''

    def get(self, request,blog_id):
        blog = get_object_or_404(Blogs,id=blog_id)
        tags = blog.tags.all()
        content = ",".join([ str(tag.name) for tag in tags])
        blog_all = Blogs.objects.all().order_by("-read_num")[:8]  # 推荐的文章
        blogs = Blogs.objects.all().order_by("?")[:8]
        news = Blogs.objects.all()
        # 上一篇
        previoud_new = Blogs.objects.filter(created_time__lt=blog.created_time).last()
        # 下一篇
        next_new = Blogs.objects.filter(created_time__gt=blog.created_time).first()
        if not request.COOKIES.get("blog_%s_read"%blog_id):
            blog.read_num += 1
            blog.save()
        blog_content_type = ContentType.objects.get_for_model(blog)
        comments = Comment.objects.filter(content_type=blog_content_type, object_id=blog.id,parent=None)
        comments_num = Comment.objects.filter(content_type=blog_content_type, object_id=blog.id).count()
        comment_form = CommentForm(initial={'content_type': blog_content_type.model, 'object_id': blog_id,"reply_comment_id":0})
        comments = comments.order_by("-comment_time")
        response = render(request,"blog/blog_show.html", locals())
        response.set_cookie("blog_%s_read"%blog_id,"true",)
        return response



def blog_list(request, tag_slug=None):
    article_list = Blogs.objects.all()
    tags = Blogs.tags.all()
    tags = random.sample(list(tags), 10)
    tag = request.GET.get('tag')
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])
        article_num = article_list.filter(tags__name__in=[tag]).count()
    paginator = Paginator(article_list, 10)  # 3 posts in each page
    page_num = request.GET.get('page', 1)
    page_of_news = paginator.get_page(page_num)
    blogs = page_of_news.object_list
    return render(request, 'blog/list.html', locals())


class TagsView(View):

    def get(self,request):
        tags = Blogs.tags.all()

        return render(request, 'blog/tags.html', locals())

templates/blog/blog_list.html
{% extends 'index/base.html' %}

    {% block title %}
<title>YLZ个人博客 -- 勤记录 懂分享</title>
    {% endblock %}
{#博客主要部分#}
{% block main %}
<section class="container">
<div class="content-wrap">
<div class="content">
  <div class="title">
	<h3 style="line-height: 1.3">YLZ-Blog博客(共{{ news_all_list.count }}篇博客)</h3>
  </div>
      {% for blog in blogs %}
      <article class="excerpt excerpt-1" style="">
      {% if blog.img_url.url != "" %}
            <a class="focus" href="{% url 'blog:show' blog.id %}" title={{ blog.title }} target="_blank" ><img class="thumb" data-original="{{ blog.img_url.url }}" src="{{ blog.img_url.url }}" alt="{{ blog.title }}"  style="display: inline;"></a>
      {% else %}
            <a class="focus" href="{% url 'blog:show' blog.id %}" title={{ blog.title }} target="_blank" ><img class="thumb" data-original="../../static/images/YLZ个人博客.png" src="../../static/images/YLZ个人博客.png" alt="{{ blog.title }}"  style="display: inline;"></a>
      {% endif %}
      <header><a class="cat" href="#" title={{ blog.blog_type }} target="_blank"  >{{ blog.blog_type }}<i></i></a>
			<h2><a href="{% url 'blog:show' blog.id %}" title={{ blog.title }} target="_blank" >{{ blog.title }}</a>
			</h2>
		</header>
		<p class="meta">
			<time class="time"><i class="glyphicon glyphicon-time"></i> {{ blog.created_time |date:"Y-m-d" }}</time>
			<span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{ blog.read_num }}</span> <span class="item article-meta-source" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="来源：{{ blog.author }}"><i class="glyphicon glyphicon-globe"></i> {{ blog.author }}</span>
		</p>
        <p class="article-tags" style="margin: 0;text-align: left">标签：
          {% for tag in blog.tags.all %}
          <a href="{% url 'blog:list' %}?tag={{ tag }}" rel="tag" >{{ tag.name }}</a>
           {% endfor %}
        </p>
		<p class="note">{{ blog.text |safe }}</p>
	</article>
  {% endfor %}

  <nav class="pagination" style="display: none;">
	<ul>
          <li class="prev-page"></li>
        {% if page_of_news.has_previous %}
            <li class="active"><a href="?page={{ page_of_news.previous_page_number }}" aria-label="Previous">上一页</a></li>
        {% else %}
            <a aria-hidden="true">上一页</a>
        {% endif %}
            {% if page_of_news.has_next %}
          <li class="next-page"><a href="?page={{ page_of_news.next_page_number }}" aria-label="Next">下一页</a></li>
          {% else %}
                <a aria-hidden="true">下一页</a>
           {% endif %}
          <li><span>共 {{ paginator.num_pages }} 页</span></li>
	</ul>
  </nav>
</div>
</div>
{% endblock %}
 {% block aside %}
<aside class="sidebar">
<div class="fixed">
  <div class="widget widget_search">
	<form class="navbar-form" action="{% url 'index:search' %}" method="get">
	  <div class="input-group">
		<input type="text" name="wd" class="form-control" size="35" placeholder="请输入关键字" maxlength="15" autocomplete="off">
		<span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span> </div>
	</form>
  </div>
  <div class="widget widget_sentence">
	<h3>标签云</h3>
	<div class="widget-sentence-content">
		<ul class="plinks ptags">
            {% for tag in tags %}
			    <li><a href="{% url 'blog:list' %}?tag={{ tag }}" title="{{ tag.name }}" draggable="false">{{ tag.name }} <span class="badge"></span></a></li>
             {% endfor %}
		</ul>
	</div>
  </div>
</div>

 {% endblock %}

templates/blog/blog_show.html
{% extends "index/base.html" %}

{% block title %}
<title>{{ blog.title }} -- YLZ个人博客 </title>
{% endblock %}

{% block meta %}
<meta name="keywords" content="{{ content }}">
<meta name="description" content="{{ blog.title }}">
{% endblock %}

{% block script %}
<script type="text/javascript" src="../../static/ckeditor/ckeditor-init.js"></script>
<script type="text/javascript" src="../../static/ckeditor/ckeditor/ckeditor.js"></script>
{% endblock %}

{% block main %}
<section class="container">
<div class="content-wrap">
<div class="content">
  <header class="article-header">
	<h1 class="article-title"><a href="#" title="{{ blog.title }}" >{{ blog.title }}</a></h1>
	<div class="article-meta"> <span class="item article-meta-time">
	  <time class="time" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="发表时间：{{ blog.created_time }}"><i class="glyphicon glyphicon-time"></i> {{ blog.created_time }}</time>
	  </span> <span class="item article-meta-source" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="来源：{{ blog.author }}"><i class="glyphicon glyphicon-globe"></i> {{ blog.author }}</span> <span class="item article-meta-category" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="{{ blog.blog_type }}"><i class="glyphicon glyphicon-list"></i> <a href="#" title="MZ-NetBlog主题" >{{ blog.blog_type }}</a></span> <span class="item article-meta-views" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="浏览量：{{blog.read_num }}"><i class="glyphicon glyphicon-eye-open"></i> {{ blog.read_num }}</span> <span class="item article-meta-comment" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="评论量：{{ comments_num }}"><i class="glyphicon glyphicon-comment"></i> {{ comments_num }}</span> </div>
  </header>
  <article class="article-content">
	<p><img data-original="../../static/images/dream.png" src="../../static/images/dream.png" alt="YLZ个人博客" /></p>
	<p>{{ blog.content | safe }}</p>
    <h4><b>文章若对你有帮助，不妨扫一扫右侧的二维码打赏支持我 ^_^</b></h4><br>
	<div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a><a href="#" class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a></div>

		  <script>                  window._bd_share_config = { "common": { "bdSnsKey": {}, "bdText": "", "bdMini": "2", "bdMiniList": false, "bdPic": "", "bdStyle": "1", "bdSize": "32" }, "share": {} }; with (document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=0.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
  </article>

  <div class="article-tags">标签：
	  {% for tag in blog.tags.all %}
	  <a href="{% url 'blog:list' %}?tag={{ tag }}" rel="tag" >{{ tag.name }}</a>
	   {% endfor %}
  </div>
    <div class="title">
        {% if previoud_new %}
            <h4>上一篇：<a href="{% url 'blog:show' previoud_new.pk %}">{{ previoud_new.title }}</a></h4><br>
        {% else %}
           <h4>上一篇：暂无</h4><br>
       {% endif %}
        {% if next_new %}
            <h4>下一篇：<a href="{% url 'blog:show' next_new.pk %}">{{ next_new.title }}</a></h4><br>
        {% else %}
           <h4>下一篇：暂无最新</h4><br>
       {% endif %}
    </div>
  <div class="relates">
	<div class="title">
	  <h3>相关推荐</h3>
	</div>
	<ul>
        {% for blog in blogs %}
	  <li><a href="{% url 'blog:show' blog.id %}" title="{{ blog.title }}" >{{ blog.title }}</a></li>
        {% endfor %}
	</ul>
  </div>
  <div class="title" id="comment">
	<h3>您好：{{ user.username }} 欢迎评论 (总共有{{ comments.count }}评论)</h3>
  </div>
  <div id="respond">
      {% if user.is_authenticated %}
          <form id="comment-form"  action="{% url 'update_comment' %}" method="POST" style="overflow:hidden">{% csrf_token %}
                <div id="reply_content_container" style="display:none;">
                    <p>回复：</p>
                    <div id="reply_content"></div>
                </div>
              {% for field in comment_form %}
                    {{ field }}
                {% endfor %}
                <span id="comment_error" class="text-danger pull-left"></span><br>
                <input type="submit" class="btn btn-primary pull-right"  value="评论">
		</form>
      {% else %}
          未登录，登录之后方可评论
          <a class="btn btn-primary" href="{% url 'index:login' %}?from={{ request.get_full_path }}">登录</a>
          <span> or </span>
          <a class="btn btn-danger" href="{% url 'index:register' %}?from={{ request.get_full_path }}">注册</a>
          <div>
              <form id="comment-form" name="comment-form" action="" method="POST">{% csrf_token %}
                <div class="comment">
                    <div class="comment-box">
                        <textarea placeholder="您还未登录，请先登录后再评论。" name="comment-textarea" id="comment-textarea" cols="100%" rows="3" tabindex="3"></textarea>
                    </div>
                </div>
            </form>
          </div>
      {% endif %}
	</div>
  <div id="postcomments">
	<div id="comment_list" class="commentlist">
        {% for comment in comments %}
            <li class="comment-content">
                <div id="root_{{ comment.id }}" class="comment comment-main">
                <p><span class="address" >{{ comment.user.username }}</span><br>
                    <div id="comment_{{ comment.pk }}">{{ comment.text|safe }}</div>
                    <a class="pull-right" href="javascript:reply({{ comment.pk }});">回复</a>
                    <span class="time pull-right">({{ comment.comment_time|date:"Y-m-d H:i:s" }})</span>
                </p>
                {% for reply in comment.root_comment.all %}
                    <div class="reply" style="margin-left: 2em;">
                        <p><span class="address" >{{ reply.user.username }}</span>回复{{ reply.reply_to.username }}：
                            <div id="comment_{{ reply.pk }}">{{ reply.text|safe }}</div><a class="pull-right" href="javascript:reply({{ reply.pk }});">回复</a>
                            <span class="time pull-right">({{ reply.comment_time|date:"Y-m-d H:i:s" }})</span></p>
                    </div>
                {% endfor %}
            </div></li>
        {% empty %}
            <span id="no_comment">暂无评论</span>
        {% endfor %}
    </div>
  </div>
</div>
</div>
    {% endblock %}

    {% block aside %}
<aside class="sidebar">
<div class="fixed">
  <div class="widget widget-tabs">
	<ul class="nav nav-tabs" role="tablist">
	  <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab" data-toggle="tab" draggable="false">统计信息</a></li>
	  <li role="presentation"><a href="#contact" aria-controls="contact" role="tab" data-toggle="tab" draggable="false">联系站长</a></li>
	</ul>
	<div class="tab-content">
	  <div role="tabpanel" class="tab-pane contact active" id="notice">
		<h2>日志总数:
			  {{ news.count }}篇
		  </h2>
		  <h2><span id="runtime_span"></span>
                <script type="text/javascript">function show_runtime(){window.setTimeout("show_runtime()",1000);X=new
                Date("8/13/2019 0:00:00");
                Y=new Date();T=(Y.getTime()-X.getTime());M=24*60*60*1000;
                a=T/M;A=Math.floor(a);b=(a-A)*24;B=Math.floor(b);c=(b-B)*60;C=Math.floor((b-B)*60);D=Math.floor((c-C)*60);
                runtime_span.innerHTML="网站运行: "+A+"天"+B+"小时"+C+"分"+D+"秒"}show_runtime();</script></h2>
	  </div>
		<div role="tabpanel" class="tab-pane contact" id="contact">
		  <h2>QQ:
			  <a href="" target="_blank" rel="nofollow" data-toggle="tooltip" data-placement="bottom" title="" draggable="false" data-original-title="QQ:827937539">827937539</a>
		  </h2>
		  <h2>Email:
		  <a href="mailto:827937539@qq.com" target="_blank" data-toggle="tooltip" rel="nofollow" data-placement="bottom" title="" draggable="false" data-original-title="Email:827937539@qq.com">827937539@qq.com</a></h2>
	  </div>
	</div>
  </div>
  <div class="widget widget_search">
    <form class="navbar-form" action="{% url 'index:search' %}" method="get">
	    <div class="input-group">
		<input type="text" name="wd" class="form-control" size="35" placeholder="请输入关键字" maxlength="15" autocomplete="off">
		<span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span> </div>
	</form>
  </div>
</div>
     {% endblock %}

{% block script_extends %}
    <script type="text/javascript">
        $("#comment-form").submit(function(){
            // 判断是否为空
            $("#comment_error").text('');
            if(CKEDITOR.instances["id_text"].document.getBody().getText().trim()==''){
                $("#comment_error").text('评论内容不能为空');
                return false;
            }

            // 更新数据到textarea
            CKEDITOR.instances['id_text'].updateElement();

            // 异步提交
            $.ajax({
                url: "{% url 'update_comment' %}",
                type: 'POST',
                data: $(this).serialize(),
                cache: false,
                success: function(data){
                    console.log(data);
                    if(data['status']=="SUCCESS"){
                        if($('#reply_comment_id').val()=='0'){
                            // 插入评论
                            var comment_html = '<div id="root_' + data['pk'] + '" class="comment"><span>' + data['username'] + '</span><span> (' + data['comment_time'] + ')：</span><div id="comment_' + data['pk'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['id'] + ');">回复</a></div>';
                            $("#comment_list").prepend(comment_html);
                        }else{
                            // 插入回复
                            var reply_html ='<div class="reply"><span>' + data['username'] + '</span><span> (' + data['comment_time'] + ')</span><span> 回复 </span><span>' + data['reply_to'] + '：</span><div id="comment_' + data['id'] + '">' + data['text'] + '</div><a href="javascript:reply(' + data['id'] + ');">回复</a></div>';
                            $("#root_" + data['root_pk']).append(reply_html);
                        }

                        // 清空编辑框的内容
                        CKEDITOR.instances['id_text'].setData('');
                        $('#reply_content_container').hide();
                        $('#reply_comment_id').val('0');
                        $('#no_comment').remove();
                    }else{
                        // 显示错误信息
                        $("#comment_error").text(data['message']);
                    }
                },
                error: function(xhr){
                    console.log(xhr);
                }
            });
            return false;
        });
        function reply(reply_comment_id){
            // 设置值
            $('#reply_comment_id').val(reply_comment_id);
            var html = $("#comment_" + reply_comment_id).html();
            $('#reply_content').html(html);
            $('#reply_content_container').show();

            $('html').animate({scrollTop: $('#comment-form').offset().top - 60}, 300, function(){
                CKEDITOR.instances['id_text'].focus();
            });
        }
    </script>

{% endblock %}

templates/blog/tags.html
{% extends "index/base2.html" %}
{% block title %}
<title>标签云 -- YLZ-Blog</title>
{% endblock %}

{% block main %}
    <div class="panel panel-default">
        <div class="panel-heading" style="text-align: center">
            <h3 class="panel-title"><b>标签云</b></h3>
        </div>

        <div class="panel-body">
            <div class="article-tags" >
              {% for tag in tags %}
                <a href="{% url 'blog:list' %}?tag={{ tag }}" rel="tag" style="margin: 8px;font-size: 15px">{{ tag.name }}</a>
              {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}